openapi: 3.0.3
info:
  title: EdenShop
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/v1/auth/login:
    post:
      summary: ''
      operationId: postApiV1AuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/v1/auth/register:
    post:
      summary: ''
      operationId: postApiV1AuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/v1/auth/logout:
    post:
      summary: ''
      operationId: postApiV1AuthLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/v1/products:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  products:
                    -
                      id: 9c57884c-11ae-4642-bef3-5e42722a5a84
                      seller_id: 9c57872e-9440-443d-9801-dcfd8d2fe537
                      upload_id: UP-6675D27B4C090
                      product_name: Miku
                      product_desc: 'minuman susu dengan berbagai varian rasa'
                      stock: 11
                      price: '50000'
                      brand: Mayora
                      created_at: '2024-06-21T19:20:27.000000Z'
                      updated_at: '2024-06-21T19:23:56.000000Z'
                      upload:
                        id: UP-6675D27B4C090
                        user_id: 9c57872e-9440-443d-9801-dcfd8d2fe537
                        image: 'http://localhost:8000/storage/products/aJsrpPLjVypsw9JGl8hXBo0PL2r67466YVaCcxMn.jpg'
                        created_at: '2024-06-21T19:20:27.000000Z'
                        updated_at: '2024-06-21T19:20:27.000000Z'
                      seller:
                        id: 9c57872e-9440-443d-9801-dcfd8d2fe537
                        name: Yahya
                        about: null
                        email: aya@account.com
                        phone: '62899966435536'
                        role: seller
                        email_verified_at: '2024-06-21T19:17:20.000000Z'
                        address: null
                        avatar_url: 'https://www.gravatar.com/avatar/f214191b712acbb4095ee1f1466033b8'
                        created_at: '2024-06-21T19:17:20.000000Z'
                        updated_at: '2024-06-21T19:17:20.000000Z'
                    -
                      id: 9c5788e0-4094-49b6-82a7-f88d6162ac47
                      seller_id: 9c57872d-52b1-4085-8420-980e95ac411f
                      upload_id: UP-6675D2DC778D9
                      product_name: Bengbeng
                      product_desc: 'Snack krunchy dengan lapisan karamel yang enak'
                      stock: 11
                      price: '25000'
                      brand: Mayora
                      created_at: '2024-06-21T19:22:04.000000Z'
                      updated_at: '2024-06-21T19:24:34.000000Z'
                      upload:
                        id: UP-6675D2DC778D9
                        user_id: 9c57872d-52b1-4085-8420-980e95ac411f
                        image: 'http://localhost:8000/storage/products/AAB2ldRTTHV8rkfP1cA9ZJrI5YapMVB4Kb6cwVVG.jpg'
                        created_at: '2024-06-21T19:22:04.000000Z'
                        updated_at: '2024-06-21T19:22:04.000000Z'
                      seller:
                        id: 9c57872d-52b1-4085-8420-980e95ac411f
                        name: Ucup
                        about: null
                        email: ucup@account.com
                        phone: '6258954384758'
                        role: seller
                        email_verified_at: '2024-06-21T19:17:19.000000Z'
                        address: null
                        avatar_url: 'https://www.gravatar.com/avatar/c967e0eef29cb6a6e344bdd10480d178'
                        created_at: '2024-06-21T19:17:19.000000Z'
                        updated_at: '2024-06-21T19:17:19.000000Z'
                properties:
                  status:
                    type: string
                    example: success
                  products:
                    type: array
                    example:
                      -
                        id: 9c57884c-11ae-4642-bef3-5e42722a5a84
                        seller_id: 9c57872e-9440-443d-9801-dcfd8d2fe537
                        upload_id: UP-6675D27B4C090
                        product_name: Miku
                        product_desc: 'minuman susu dengan berbagai varian rasa'
                        stock: 11
                        price: '50000'
                        brand: Mayora
                        created_at: '2024-06-21T19:20:27.000000Z'
                        updated_at: '2024-06-21T19:23:56.000000Z'
                        upload:
                          id: UP-6675D27B4C090
                          user_id: 9c57872e-9440-443d-9801-dcfd8d2fe537
                          image: 'http://localhost:8000/storage/products/aJsrpPLjVypsw9JGl8hXBo0PL2r67466YVaCcxMn.jpg'
                          created_at: '2024-06-21T19:20:27.000000Z'
                          updated_at: '2024-06-21T19:20:27.000000Z'
                        seller:
                          id: 9c57872e-9440-443d-9801-dcfd8d2fe537
                          name: Yahya
                          about: null
                          email: aya@account.com
                          phone: '62899966435536'
                          role: seller
                          email_verified_at: '2024-06-21T19:17:20.000000Z'
                          address: null
                          avatar_url: 'https://www.gravatar.com/avatar/f214191b712acbb4095ee1f1466033b8'
                          created_at: '2024-06-21T19:17:20.000000Z'
                          updated_at: '2024-06-21T19:17:20.000000Z'
                      -
                        id: 9c5788e0-4094-49b6-82a7-f88d6162ac47
                        seller_id: 9c57872d-52b1-4085-8420-980e95ac411f
                        upload_id: UP-6675D2DC778D9
                        product_name: Bengbeng
                        product_desc: 'Snack krunchy dengan lapisan karamel yang enak'
                        stock: 11
                        price: '25000'
                        brand: Mayora
                        created_at: '2024-06-21T19:22:04.000000Z'
                        updated_at: '2024-06-21T19:24:34.000000Z'
                        upload:
                          id: UP-6675D2DC778D9
                          user_id: 9c57872d-52b1-4085-8420-980e95ac411f
                          image: 'http://localhost:8000/storage/products/AAB2ldRTTHV8rkfP1cA9ZJrI5YapMVB4Kb6cwVVG.jpg'
                          created_at: '2024-06-21T19:22:04.000000Z'
                          updated_at: '2024-06-21T19:22:04.000000Z'
                        seller:
                          id: 9c57872d-52b1-4085-8420-980e95ac411f
                          name: Ucup
                          about: null
                          email: ucup@account.com
                          phone: '6258954384758'
                          role: seller
                          email_verified_at: '2024-06-21T19:17:19.000000Z'
                          address: null
                          avatar_url: 'https://www.gravatar.com/avatar/c967e0eef29cb6a6e344bdd10480d178'
                          created_at: '2024-06-21T19:17:19.000000Z'
                          updated_at: '2024-06-21T19:17:19.000000Z'
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: 9c57884c-11ae-4642-bef3-5e42722a5a84
                        seller_id:
                          type: string
                          example: 9c57872e-9440-443d-9801-dcfd8d2fe537
                        upload_id:
                          type: string
                          example: UP-6675D27B4C090
                        product_name:
                          type: string
                          example: Miku
                        product_desc:
                          type: string
                          example: 'minuman susu dengan berbagai varian rasa'
                        stock:
                          type: integer
                          example: 11
                        price:
                          type: string
                          example: '50000'
                        brand:
                          type: string
                          example: Mayora
                        created_at:
                          type: string
                          example: '2024-06-21T19:20:27.000000Z'
                        updated_at:
                          type: string
                          example: '2024-06-21T19:23:56.000000Z'
                        upload:
                          type: object
                          properties:
                            id:
                              type: string
                              example: UP-6675D27B4C090
                            user_id:
                              type: string
                              example: 9c57872e-9440-443d-9801-dcfd8d2fe537
                            image:
                              type: string
                              example: 'http://localhost:8000/storage/products/aJsrpPLjVypsw9JGl8hXBo0PL2r67466YVaCcxMn.jpg'
                            created_at:
                              type: string
                              example: '2024-06-21T19:20:27.000000Z'
                            updated_at:
                              type: string
                              example: '2024-06-21T19:20:27.000000Z'
                        seller:
                          type: object
                          properties:
                            id:
                              type: string
                              example: 9c57872e-9440-443d-9801-dcfd8d2fe537
                            name:
                              type: string
                              example: Yahya
                            about:
                              type: string
                              example: null
                            email:
                              type: string
                              example: aya@account.com
                            phone:
                              type: string
                              example: '62899966435536'
                            role:
                              type: string
                              example: seller
                            email_verified_at:
                              type: string
                              example: '2024-06-21T19:17:20.000000Z'
                            address:
                              type: string
                              example: null
                            avatar_url:
                              type: string
                              example: 'https://www.gravatar.com/avatar/f214191b712acbb4095ee1f1466033b8'
                            created_at:
                              type: string
                              example: '2024-06-21T19:17:20.000000Z'
                            updated_at:
                              type: string
                              example: '2024-06-21T19:17:20.000000Z'
      tags:
        - Endpoints
      security: []
  '/api/v1/products/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  product:
                    id: 9c57884c-11ae-4642-bef3-5e42722a5a84
                    seller_id: 9c57872e-9440-443d-9801-dcfd8d2fe537
                    upload_id: UP-6675D27B4C090
                    product_name: Miku
                    product_desc: 'minuman susu dengan berbagai varian rasa'
                    stock: 11
                    price: '50000'
                    brand: Mayora
                    created_at: '2024-06-21T19:20:27.000000Z'
                    updated_at: '2024-06-21T19:23:56.000000Z'
                properties:
                  status:
                    type: string
                    example: success
                  product:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 9c57884c-11ae-4642-bef3-5e42722a5a84
                      seller_id:
                        type: string
                        example: 9c57872e-9440-443d-9801-dcfd8d2fe537
                      upload_id:
                        type: string
                        example: UP-6675D27B4C090
                      product_name:
                        type: string
                        example: Miku
                      product_desc:
                        type: string
                        example: 'minuman susu dengan berbagai varian rasa'
                      stock:
                        type: integer
                        example: 11
                      price:
                        type: string
                        example: '50000'
                      brand:
                        type: string
                        example: Mayora
                      created_at:
                        type: string
                        example: '2024-06-21T19:20:27.000000Z'
                      updated_at:
                        type: string
                        example: '2024-06-21T19:23:56.000000Z'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 9c57884c-11ae-4642-bef3-5e42722a5a84
        required: true
        schema:
          type: string
  /api/v1/orders:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/v1/orders/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the order.'
        example: totam
        required: true
        schema:
          type: string
  /api/v1/orders/create:
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/v1/seller/products/create:
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/v1/seller/products/{id}':
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 9c57884c-11ae-4642-bef3-5e42722a5a84
        required: true
        schema:
          type: string
  /api/v1/seller/orders:
    get:
      summary: ''
      operationId: getApiV1SellerOrders
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/v1/seller/orders/{id}':
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the order.'
        example: dolor
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
